###
# @name listdumps
GET {{$dotenv ABAP_ADT_URL}}/sap/bc/adt/runtime/dumps
Authorization: Basic {{$dotenv ABAP_ADT_USER}} {{$dotenv ABAP_ADT_PASSWORD}}
Accept: application/atom+xml;type=feed

###
# @name getDump
GET {{$dotenv ABAP_ADT_URL}}/sap/bc/adt/runtime/dump/{{$dotenv ABAP_APITEST_DUMPID}}
Authorization: Basic {{$dotenv ABAP_ADT_USER}} {{$dotenv ABAP_ADT_PASSWORD}}
Accept: text/html

###
# @name getDump_xml
GET {{$dotenv ABAP_ADT_URL}}/sap/bc/adt/runtime/dump/{{$dotenv ABAP_APITEST_DUMPID}}
Authorization: Basic {{$dotenv ABAP_ADT_USER}} {{$dotenv ABAP_ADT_PASSWORD}}
Accept: application/vnd.sap.adt.runtime.dump.v1+xml

###
# @name getDump_unformatted
GET {{$dotenv ABAP_ADT_URL}}/sap/bc/adt/runtime/dump/{{$dotenv ABAP_APITEST_DUMPID}}/unformatted
Authorization: Basic {{$dotenv ABAP_ADT_USER}} {{$dotenv ABAP_ADT_PASSWORD}}
Accept: text/plain
###
##
# @name getDump_unformatted_de
GET {{$dotenv ABAP_ADT_URL}}/sap/bc/adt/runtime/dump/{{$dotenv ABAP_APITEST_DUMPID}}/unformatted
Authorization: Basic {{$dotenv ABAP_ADT_USER}} {{$dotenv ABAP_ADT_PASSWORD}}
Accept: text/plain